@extends('includes.navbar')

@section('row')
<div class="menu-line menu-line-secondary menu-line-submenu">

    <div class="menu-items">
        <a class="menu-item" href="https://ilyabirman.ru/meanwhile/tags/design/"><div class="menu-link">Дизайн</div></a><a class="menu-item" href="https://ilyabirman.ru/meanwhile/tags/ui/"><div class="menu-link">Интерфейс</div></a><a class="menu-item" href="https://ilyabirman.ru/meanwhile/tags/world/"><div class="menu-link">Мир</div></a><a class="menu-item" href="https://ilyabirman.ru/meanwhile/tags/negotiations/"><div class="menu-link">Переговоры</div></a><a class="menu-item" href="https://ilyabirman.ru/meanwhile/tags/russian-language/"><div class="menu-link">Русский язык</div></a><a class="menu-item" href="https://ilyabirman.ru/meanwhile/tags/books/"><div class="menu-link">Книги</div></a><a class="menu-item" href="https://ilyabirman.ru/meanwhile/tags/economy/"><div class="menu-link">Экономика</div></a><a class="menu-item" href="https://ilyabirman.ru/meanwhile/tags/philosophy/"><div class="menu-link">Философия</div></a><a class="menu-item" href="https://ilyabirman.ru/meanwhile/tags/talks/"><div class="menu-link">Доклады</div></a>
    </div>

</div>
@endsection

@section('row-mob')
    <div class="mobile-menu-line mobile-menu-line-secondary mobile-menu-line-submenu">
        <div class="mobile-menu-items">
            <a class="mobile-menu-item" href="https://ilyabirman.ru/meanwhile/tags/design/"><div class="mobile-menu-link">Дизайн</div><svg class="mobile-menu-arrow" xmlns="http://www.w3.org/2000/svg" width="8" height="8"><path d="M0,0h8v8H6.5V1.5H0z"></path></svg></a><a class="mobile-menu-item" href="https://ilyabirman.ru/meanwhile/tags/ui/"><div class="mobile-menu-link">Интерфейс</div><svg class="mobile-menu-arrow" xmlns="http://www.w3.org/2000/svg" width="8" height="8"><path d="M0,0h8v8H6.5V1.5H0z"></path></svg></a><a class="mobile-menu-item" href="https://ilyabirman.ru/meanwhile/tags/world/"><div class="mobile-menu-link">Мир</div><svg class="mobile-menu-arrow" xmlns="http://www.w3.org/2000/svg" width="8" height="8"><path d="M0,0h8v8H6.5V1.5H0z"></path></svg></a><a class="mobile-menu-item" href="https://ilyabirman.ru/meanwhile/tags/negotiations/"><div class="mobile-menu-link">Переговоры</div><svg class="mobile-menu-arrow" xmlns="http://www.w3.org/2000/svg" width="8" height="8"><path d="M0,0h8v8H6.5V1.5H0z"></path></svg></a><a class="mobile-menu-item" href="https://ilyabirman.ru/meanwhile/tags/russian-language/"><div class="mobile-menu-link">Русский язык</div><svg class="mobile-menu-arrow" xmlns="http://www.w3.org/2000/svg" width="8" height="8"><path d="M0,0h8v8H6.5V1.5H0z"></path></svg></a><a class="mobile-menu-item" href="https://ilyabirman.ru/meanwhile/tags/books/"><div class="mobile-menu-link">Книги</div><svg class="mobile-menu-arrow" xmlns="http://www.w3.org/2000/svg" width="8" height="8"><path d="M0,0h8v8H6.5V1.5H0z"></path></svg></a><a class="mobile-menu-item" href="https://ilyabirman.ru/meanwhile/tags/economy/"><div class="mobile-menu-link">Экономика</div><svg class="mobile-menu-arrow" xmlns="http://www.w3.org/2000/svg" width="8" height="8"><path d="M0,0h8v8H6.5V1.5H0z"></path></svg></a><a class="mobile-menu-item" href="https://ilyabirman.ru/meanwhile/tags/philosophy/"><div class="mobile-menu-link">Философия</div><svg class="mobile-menu-arrow" xmlns="http://www.w3.org/2000/svg" width="8" height="8"><path d="M0,0h8v8H6.5V1.5H0z"></path></svg></a><a class="mobile-menu-item" href="https://ilyabirman.ru/meanwhile/tags/talks/"><div class="mobile-menu-link">Доклады</div><svg class="mobile-menu-arrow" xmlns="http://www.w3.org/2000/svg" width="8" height="8"><path d="M0,0h8v8H6.5V1.5H0z"></path></svg></a>
            <a class="mobile-menu-item" href="/meanwhile/found/штангенциркуль/" style="box-shadow: none; background: none"><span style="display: inline-block; width: 32px; height: 32px"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16"><path stroke="none" fill-rule="evenodd" clip-rule="evenodd" d="M16 14.5l-4.399-4.399a6.212 6.212 0 001.148-3.602 6.25 6.25 0 10-12.5 0 6.25 6.25 0 006.251 6.25 6.212 6.212 0 003.602-1.148L14.5 16l1.5-1.5zM1.25 6.501a5.251 5.251 0 1110.502 0 5.251 5.251 0 01-10.502 0z"></path></svg></span></a>
        </div>
    </div>
@endsection
